export { default as Home } from './Home'
export { default as Education } from './Education'
export { default as Skills } from './Skills'
export { default as Contacts } from './Contacts'
export { default as LogIn } from './LogIn'